version: '3'
services:
   db:
     image: core/postgresql
     volumes:       
       - "./updated_config.toml:/updated_config.toml"
   railsapp:
      image: originname/myrailsapp
      ports:
        - 8000:8000
      links: 
       - db
      command: --peer db --bind database:postgresql.default 